# Generated by Django 5.0.1 on 2024-03-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_prodcut_details_bestseller_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img1',
            field=models.ImageField(blank=True, default='path/to/default_image.jpg', null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img2',
            field=models.ImageField(blank=True, default='path/to/default_image.jpg', null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img3',
            field=models.ImageField(blank=True, default='path/to/default_image.jpg', null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img4',
            field=models.ImageField(blank=True, default='path/to/default_image.jpg', null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img5',
            field=models.ImageField(blank=True, default='path/to/default_image.jpg', null=True, upload_to='product_view_slider_img/'),
        ),
    ]
