# Generated by Django 5.0.1 on 2024-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bestseller_extra_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img1',
            field=models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img2',
            field=models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img3',
            field=models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img4',
            field=models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='extra_img5',
            field=models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/'),
        ),
    ]
