# Generated by Django 5.0.1 on 2024-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_productmonth_bestseller_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailbg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_img', models.ImageField(upload_to='email_section_image/')),
            ],
        ),
    ]
