# Generated by Django 5.0.1 on 2024-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_emailbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_img', models.ImageField(upload_to='instagram_images/')),
            ],
        ),
    ]
