# Generated by Django 5.0.1 on 2024-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_insta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insta',
            new_name='insta_post',
        ),
    ]
