# Generated by Django 5.0.1 on 2024-03-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_insta_insta_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta_post',
            name='insta_post_link',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
