# Generated by Django 5.0.1 on 2024-03-07 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productmonth_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='category_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
