# Generated by Django 5.0.1 on 2024-03-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bestseller_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='category_name',
            new_name='category_nam',
        ),
    ]
