# Generated by Django 5.0.1 on 2024-03-07 05:03

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_category_name_bestseller_category_nam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allproduct_img', models.ImageField(upload_to='allproduct_img')),
                ('allproduct_name', models.CharField(max_length=800)),
                ('allproduct_price', models.PositiveIntegerField()),
                ('allproduct_details', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='allproduct_name', unique=True)),
                ('extra_img1', models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/')),
                ('extra_img2', models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/')),
                ('extra_img3', models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/')),
                ('extra_img4', models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/')),
                ('extra_img5', models.ImageField(blank=True, null=True, upload_to='product_view_slider_img/')),
                ('allcategory_nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
