# Generated by Django 5.0.1 on 2024-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_allproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='allcategory_nam',
            new_name='category_nam',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='allproduct_details',
            new_name='product_details',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='allproduct_img',
            new_name='product_img',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='allproduct_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='allproduct_price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='allproduct',
            name='add_in_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bestseller',
        ),
    ]
