# Generated by Django 5.0.1 on 2024-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_allcategory_nam_allproduct_category_nam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_post',
            name='insta_post_link',
            field=models.URLField(blank=True, default='#', max_length=800, null=True),
        ),
    ]
